### ISSUE TITLE
Can't get example running correctly.

### ISSUE THREAD

**Issue by cosmicspacedragon** [daboross/screeps-in-rust-via-wasm#109] opened 2018-12-26 10:52 UTC
When I try compiling and using the example code it seems to work, right up to the moment when the first harvester spawns. That's when the console gets flooded with the same error on repeat.
```
[11:47:39 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:40 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:41 AM](INFO) screeps_starter_rust: running memory cleanup
[11:47:41 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:42 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:42 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:43 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:43 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:44 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:44 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:45 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:45 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:46 AM](INFO) screeps_starter_rust: done! cpu: 0
[11:47:47 AM]caught exception: ReferenceError: return_ is not defined
[11:47:47 AM]stack trace: ReferenceError: return_ is not defined
    at eval (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :837:100)
    at __cargo_web_snippet_f287832d55a875e04e3aaf40dc55db0e49c6f9f5 (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :837:126)
    at screeps_starter_rust::game_loop::h00ced329833a6c89 ([58]+5741)
    at _$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$$RP$$RP$$C$$u20$F$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h564092255a801633 ([53]+436)
    at Object.Module.STDWEB_PRIVATE.dyncall (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :439:40)
    at output (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :139:39)
    at Object.Module.STDWEB_PRIVATE.from_js.module.exports.loop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :729:154)
    at __run___mainLoop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :1:17253)
    at eval (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :2:4)
    at Object.exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347)
[11:47:47 AM]resetting VM next tick.
[11:47:48 AM]caught exception: ReferenceError: return_ is not defined
[11:47:48 AM]stack trace: ReferenceError: return_ is not defined
    at eval (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :837:100)
    at __cargo_web_snippet_f287832d55a875e04e3aaf40dc55db0e49c6f9f5 (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :837:126)
    at screeps_starter_rust::game_loop::h00ced329833a6c89 ([58]+5741)
    at _$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$$RP$$RP$$C$$u20$F$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h564092255a801633 ([53]+436)
    at Object.Module.STDWEB_PRIVATE.dyncall (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :439:40)
    at output (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :139:39)
    at Object.Module.STDWEB_PRIVATE.from_js.module.exports.loop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :729:154)
    at Object.module.exports.loop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :729:431)
    at __run___mainLoop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :1:17253)
    at eval (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :2:4)
[11:47:48 AM]resetting VM next tick.
[11:47:49 AM]caught exception: ReferenceError: return_ is not defined
[11:47:49 AM]stack trace: ReferenceError: return_ is not defined
    at eval (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :837:100)
    at __cargo_web_snippet_f287832d55a875e04e3aaf40dc55db0e49c6f9f5 (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :837:126)
    at screeps_starter_rust::game_loop::h00ced329833a6c89 ([58]+5741)
    at _$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$$RP$$RP$$C$$u20$F$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h564092255a801633 ([53]+436)
    at Object.Module.STDWEB_PRIVATE.dyncall (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :439:40)
    at output (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :139:39)
    at Object.Module.STDWEB_PRIVATE.from_js.module.exports.loop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :729:154)
    at Object.module.exports.loop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :729:431)
    at __run___mainLoop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :1:17253)
    at eval (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :2:4)
[11:47:49 AM]resetting VM next tick.
[11:47:50 AM]caught exception: ReferenceError: return_ is not defined
[11:47:50 AM]stack trace: ReferenceError: return_ is not defined
    at eval (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :837:100)
    at __cargo_web_snippet_f287832d55a875e04e3aaf40dc55db0e49c6f9f5 (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :837:126)
    at screeps_starter_rust::game_loop::h00ced329833a6c89 ([58]+5741)
    at _$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$$RP$$RP$$C$$u20$F$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h564092255a801633 ([53]+436)
    at Object.Module.STDWEB_PRIVATE.dyncall (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :439:40)
    at output (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :139:39)
    at Object.Module.STDWEB_PRIVATE.from_js.module.exports.loop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :729:154)
    at Object.module.exports.loop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :729:431)
    at __run___mainLoop (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :1:17253)
    at eval (eval at exports.evalCode (blob:chrome-extension://cknihipnnkgolgdlfodbibfmdmhhbmlb/9906ab3e-7b7b-450a-b439-ef3e772ada7b:2:11347), :2:4)
[11:47:50 AM]resetting VM next tick.
```

**Comment by daboross** [comment] 2018-12-26 21:19
I'll see if I can reproduce this- I haven't run into it before but package updates might have caused something. Last time I built screeps-starter-rust it ran correctly (on the main world, at least), but when I look at the code `return_` isn't in it anywhere.

**Comment by daboross** [comment] 2018-12-26 21:58
After updating everything on my machine and rebuilding, I still can't seem to reproduce this.

Could you possibly upload the `target/main.js` file generated in your local project? It might help see what's different.

**Comment by daboross** [comment] 2018-12-28 08:46
Thanks! Looking at the `main.js` was definitely helpful.

After messing around with my system more, I've been able to reproduce it. Must not have cleaned something out correctly before, but I'm not sure what.

The problem seems to be with `stdweb` version `0.4.12` - after fully cleaning everything, it fails with version 0.4.12, but succeeds with 0.4.10. I've submitted an issue here: https://github.com/koute/stdweb/issues/316.

For now, I would recommend manually downgrading to stdweb 0.4.10. This should work:

```console
$ cargo update --package stdweb --precise 0.4.10
```

Let me know if that fixes it for you?

**Comment by ASalvail** [comment] 2019-01-13 01:45
Can anyone confirm that this is fixed with `stdweb 0.4.13`?

**Comment by cosmicspacedragon** [comment] 2019-01-13 17:40
Can confirm.

**Comment by ASalvail** [comment] 2019-01-13 21:56
Thanks. I'll close this then.

**Closed by ASalvail** 2019-01-13 21:56 UTC
Labels: A-screeps-game-api, C-bug
